# Generated by Django 6.0.4 on 2026-04-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('emailVerified', models.BooleanField(default=False)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testId', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('completedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('materialId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('expiresAt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewId', models.CharField(max_length=255)),
                ('textSnippet', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('positionInText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('materialId', models.CharField(max_length=255)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('filePath', models.CharField(max_length=255)),
                ('fileType', models.CharField(max_length=50)),
                ('sizeBytes', models.BigIntegerField(default=0)),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('authorId', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=0)),
                ('isVerified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialId', models.CharField(max_length=255)),
                ('moderatorId', models.CharField(max_length=255)),
                ('decision', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateId', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('testResultId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('isRead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('scope', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workId', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0)),
                ('status', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('qType', models.CharField(max_length=50)),
                ('correctAnswer', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporterId', models.CharField(max_length=255)),
                ('targetType', models.CharField(max_length=50)),
                ('targetId', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('expiresAt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('materialId', models.CharField(max_length=255)),
                ('votedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('studentId', models.CharField(max_length=255)),
                ('packageId', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('assignedModeratorId', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workId', models.CharField(max_length=255)),
                ('moderatorId', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('generalComment', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExtLearnerUJ.user')),
            ],
            bases=('ExtLearnerUJ.user',),
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExtLearnerUJ.user')),
            ],
            bases=('ExtLearnerUJ.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExtLearnerUJ.user')),
            ],
            bases=('ExtLearnerUJ.user',),
        ),
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('testresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExtLearnerUJ.testresult')),
                ('areaScores', models.JSONField(default=dict)),
            ],
            bases=('ExtLearnerUJ.testresult',),
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExtLearnerUJ.test')),
            ],
            bases=('ExtLearnerUJ.test',),
        ),
    ]
